'use strict';

angular.module('cocjs').factory('StatusAffects', function (StatusAffectType, CombatStatusAffect) {
	return {
		// Non-combat player perks
		AllNaturalOnaholeUsed : new StatusAffectType('all-natural onahole used'),
		AteEgg : new StatusAffectType('ateEgg'),
		AnemoneArousal : new StatusAffectType('Anemone Arousal'),
		BimboChampagne : new StatusAffectType('Bimbo Champagne'),
		Birthed : new StatusAffectType('Birthed'),
		BirthedImps : new StatusAffectType('Birthed Imps'),
		BlackCatBeer : new StatusAffectType('Black Cat Beer'),
		BlackNipples : new StatusAffectType('Black Nipples'),
		BlowjobOn : new StatusAffectType('BlowjobOn'),
		BoatDiscovery : new StatusAffectType('Boat Discovery'),
		BonusACapacity : new StatusAffectType('Bonus aCapacity'),
		BonusVCapacity : new StatusAffectType('Bonus vCapacity'),
		BottledMilk : new StatusAffectType('Bottled Milk'),
		BreastsMilked : new StatusAffectType('Breasts Milked'),
		BSwordBroken : new StatusAffectType('BSwordBroken'),
		BuiltMilker : new StatusAffectType('BUILT: Milker'),
		BurpChanged : new StatusAffectType('Burp Changed'),
		ButtStretched : new StatusAffectType('ButtStretched'),
		CampAnemoneTrigger : new StatusAffectType('Camp Anemone Trigger'),
		CampMarble : new StatusAffectType('Camp Marble'),
		CampRathazul : new StatusAffectType('Camp Rathazul'),
		ClaraCombatRounds : new StatusAffectType('Clara Combat Rounds'),
		ClaraFoughtInCamp : new StatusAffectType('Clara Fought In Camp'),
		CockPumped : new StatusAffectType('Cock Pumped'),
		Contraceptives : new StatusAffectType('Contraceptives'),
		CuntStretched : new StatusAffectType('CuntStretched'),
		DefenseCanopy : new StatusAffectType('Defense: Canopy'),
		DeluxeOnaholeUsed : new StatusAffectType('deluxe onahole used'),
		DogWarning : new StatusAffectType('dog warning'),
		DragonBreathBoost : new StatusAffectType('Dragon Breath Boost'),
		DragonBreathCooldown : new StatusAffectType('Dragon Breath Cooldown'),
		DungeonShutDown : new StatusAffectType('DungeonShutDown'),
		Dysfunction : new StatusAffectType('dysfunction'),
		Edryn : new StatusAffectType('Edryn'),
		Eggchest : new StatusAffectType('eggchest'),
		Eggs : new StatusAffectType('eggs'),
		EmberFuckCooldown : new StatusAffectType('ember fuck cooldown'),
		EmberNapping : new StatusAffectType('Ember Napping'),
		EverRapedJojo : new StatusAffectType('Ever Raped Jojo'),
		Exgartuan : new StatusAffectType('Exgartuan'),
		ExploredDeepwoods : new StatusAffectType('exploredDeepwoods'),
		FactoryOmnibusDefeated : new StatusAffectType('FactoryOmnibusDefeated'),
		FactoryOverload : new StatusAffectType('FactoryOverload'),
		FactoryIncubusDefeated : new StatusAffectType('FactoryIncubusDefeated'),
		FactorySuccubusDefeated : new StatusAffectType('FactorySuccubusDefeated'),
		FaerieFemFuck : new StatusAffectType('Faerie Fem Fuck'),
		FaerieFucked : new StatusAffectType('Faerie Fucked'),
		FappedGenderless : new StatusAffectType('fapped genderless'),
		Feeder : new StatusAffectType('Feeder'),
		Fertilized : new StatusAffectType('Fertilized'),
		FetishOn : new StatusAffectType('fetishON'),
		FoundFactory : new StatusAffectType('Found Factory'),
		FuckedMarble : new StatusAffectType('FuckedMarble'),
		Goojob : new StatusAffectType('GOOJOB'),
		GooStuffed : new StatusAffectType('gooStuffed'),
		Groundpound : new StatusAffectType('Groundpound'),
		HairdresserMeeting : new StatusAffectType('hairdresser meeting'),
		Hangover : new StatusAffectType('Hangover'),
		Heat : new StatusAffectType('heat'),
		HorseWarning : new StatusAffectType('horse warning'),
		ImmolationSpell : new StatusAffectType('Immolation Spell'),
		ImpGangBang : new StatusAffectType('Imp GangBang'),
		IncubusBribed : new StatusAffectType('IncubusBribed'),
		Infested : new StatusAffectType('infested'),
		IzmaBlowing : new StatusAffectType('IzmaBlowing'),
		IzumisPipeSmoke : new StatusAffectType('Izumis Pipe Smoke'),
		JerkingIzma : new StatusAffectType('JerkingIzma'),
		Jizzpants : new StatusAffectType('Jizzpants'),
		JojoMeditationCount : new StatusAffectType('Jojo Meditation Count'),
		JojoNightWatch : new StatusAffectType('JojoNightWatch'),
		JojoTFOffer : new StatusAffectType('JojoTFOffer'),
		Kelt : new StatusAffectType('Kelt'),
		KeltBJ : new StatusAffectType('KeltBJ'),
		KeltBadEndWarning : new StatusAffectType('Kelt Bad End Warning'),
		KeltOff : new StatusAffectType('KeltOff'),
		KnowsArouse : new StatusAffectType('Knows Arouse'),
		KnowsBlind : new StatusAffectType('Knows Blind'),
		KnowsCharge : new StatusAffectType('Knows Charge'),
		KnowsHeal : new StatusAffectType('Knows Heal'),
		KnowsMight : new StatusAffectType('Knows Might'),
		KnowsWhitefire : new StatusAffectType('Knows Whitefire'),
		LactationEndurance : new StatusAffectType('Lactation Endurance'),
		LactationReduction : new StatusAffectType('Lactation Reduction'),
		LactationReduc0 : new StatusAffectType('Lactation Reduc0'),
		LactationReduc1 : new StatusAffectType('Lactation Reduc1'),
		LactationReduc2 : new StatusAffectType('Lactation Reduc2'),
		LactationReduc3 : new StatusAffectType('Lactation Reduc3'),
		LootEgg : new StatusAffectType('lootEgg'),
		LostVillagerSpecial : new StatusAffectType('lostVillagerSpecial'),
		Luststick : new StatusAffectType('Luststick'),
		LustStickApplied : new StatusAffectType('Lust Stick Applied'),
		LustyTongue : new StatusAffectType('LustyTongue'),
		MalonVisitedPostAddiction : new StatusAffectType('Malon Visited Post Addiction'),
		MaraeComplete : new StatusAffectType('Marae Complete'),
		MaraesLethicite : new StatusAffectType('Marae\'s Lethicite'),
		MaraesQuestStart : new StatusAffectType('Marae\'s Quest Start'),
		Marble : new StatusAffectType('Marble'),
		MarbleHasItem : new StatusAffectType('MarbleHasItem'),
		MarbleItemCooldown : new StatusAffectType('MarbleItemCooldown'),
		MarbleRapeAttempted : new StatusAffectType('Marble Rape Attempted'),
		MarblesMilk : new StatusAffectType('Marbles Milk'),
		MarbleSpecials : new StatusAffectType('MarbleSpecials'),
		MarbleWithdrawl : new StatusAffectType('MarbleWithdrawl'),
		Meditated : new StatusAffectType('Meditated'),
		MeanToNaga : new StatusAffectType('MeanToNaga'),
		MeetWanderer : new StatusAffectType('meet wanderer'),
		MetCorruptMarae : new StatusAffectType('Met Corrupt Marae'),
		MetMarae : new StatusAffectType('Met Marae'),
		MetRathazul : new StatusAffectType('metRathazul'),
		MetWorms : new StatusAffectType('metWorms'),
		MetWhitney : new StatusAffectType('Met Whitney'),
		Milked : new StatusAffectType('Milked'),
		MinoPlusCowgirl : new StatusAffectType('Mino + Cowgirl'),
		Naga : new StatusAffectType('Naga'),
		NakedOn : new StatusAffectType('NakedOn'),
		NoJojo : new StatusAffectType('noJojo'),
		NoMoreMarble : new StatusAffectType('No More Marble'),
		Oswald : new StatusAffectType('Oswald'),
		PlainOnaholeUsed : new StatusAffectType('plain onahole used'),
		PhoukaWhiskeyAffect : new StatusAffectType('PhoukaWhiskeyAffect'),
		PostAkbalSubmission : new StatusAffectType('Post Akbal Submission'),
		PostAnemoneBeatdown : new StatusAffectType('Post Anemone Beatdown'),
		PureCampJojo : new StatusAffectType('PureCampJojo'),
		RathazulArmor : new StatusAffectType('RathazulArmor'),
		RepeatSuccubi : new StatusAffectType('repeatSuccubi'),
		Rut : new StatusAffectType('rut'),
		SharkGirl : new StatusAffectType('Shark-Girl'),
		ShieldingSpell : new StatusAffectType('Shielding Spell'),
		SlimeCraving : new StatusAffectType('Slime Craving'),
		SlimeCravingFeed : new StatusAffectType('Slime Craving Feed'),
		SlimeCravingOutput : new StatusAffectType('Slime Craving Output'),
		SuccubiFirst : new StatusAffectType('SuccubiFirst'),
		SuccubiNight : new StatusAffectType('succubiNight'),
		TakenGroPlus : new StatusAffectType('TakenGro+'),
		TakenLactaid : new StatusAffectType('TakenLactaid'),
		Tamani : new StatusAffectType('Tamani'),									//Used only for compatibility with old save files, otherwise no longer in use
		TamaniFemaleEncounter : new StatusAffectType('Tamani Female Encounter'),	//Used only for compatibility with old save files, otherwise no longer in use
		TelAdre : new StatusAffectType('Tel\'Adre'),
		TentacleBadEndCounter : new StatusAffectType('TentacleBadEndCounter'),
		TentacleJojo : new StatusAffectType('Tentacle Jojo'),
		TensionReleased : new StatusAffectType('TensionReleased'),
		TF2 : new StatusAffectType('TF2'),
		TookBlessedSword : new StatusAffectType('Took Blessed Sword'),
		/**
		 * v1 = bonus index
		 * v2 = bonus value
		 * v3 = remaining time
		 */
		UmasMassage : new StatusAffectType('Uma\'s Massage'),
		Uniball : new StatusAffectType('Uniball'),
		UsedNaturalSelfStim : new StatusAffectType('used natural self-stim'),
		used_self_dash_stim : new StatusAffectType('used self-stim'),
		Victoria : new StatusAffectType('Victoria'),
		VoluntaryDemonpack : new StatusAffectType('Voluntary Demonpack'),
		WormOffer : new StatusAffectType('WormOffer'),
		WormPlugged : new StatusAffectType('worm plugged'),
		WormsHalf : new StatusAffectType('wormsHalf'),
		WormsOff : new StatusAffectType('wormsOff'),
		WormsOn : new StatusAffectType('wormsOn'),
		WandererDemon : new StatusAffectType('wanderer demon'),
		WandererHuman : new StatusAffectType('wanderer human'),
		Yara : new StatusAffectType('Yara'),

		// monster
		Attacks : new StatusAffectType('attacks'),
		BimboBrawl : new StatusAffectType('bimboBrawl'),
		BowCooldown : new StatusAffectType('Bow Cooldown'),
		BowDisabled : new StatusAffectType('Bow Disabled'),
		Charged : new StatusAffectType('Charged'),
		Climbed : new StatusAffectType('Climbed'),
		Concentration : new StatusAffectType('Concentration'),
		Constricted : new StatusAffectType('Constricted'),
		CoonWhip : new StatusAffectType('Coon Whip'),
		Counter : new StatusAffectType('Counter'),
		DomFight : new StatusAffectType('domfight'),
		DrankMinoCum : new StatusAffectType('drank mino cum'),
		DrankMinoCum2 : new StatusAffectType('drank mino cum2'),
		Earthshield : new StatusAffectType('Earthshield'),
		Fear : new StatusAffectType('Fear'),
		GenericRunDisabled : new StatusAffectType('Generic Run Disabled'),
		Gigafire : new StatusAffectType('Gigafire'),
		GottaOpenGift : new StatusAffectType('Gotta Open Gift'),
		HolliBurning : new StatusAffectType('Holli Burning'),
		Illusion : new StatusAffectType('Illusion'),
		ImpSkip : new StatusAffectType('ImpSkip'),
		ImpUber : new StatusAffectType('ImpUber'),
		JojoIsAssisting : new StatusAffectType('Jojo Is Assisting'),
		JojoPyre : new StatusAffectType('Jojo Pyre'),
		Keen : new StatusAffectType('keen'),
		Level : new StatusAffectType('level'),
		KitsuneFight : new StatusAffectType('Kitsune Fight'),
		LustAura : new StatusAffectType('Lust Aura'),
		LustStick : new StatusAffectType('LustStick'),
		Milk : new StatusAffectType('milk'),
		MilkyUrta : new StatusAffectType('Milky Urta'),
		MinoMilk : new StatusAffectType('Mino Milk'),
		MinotaurEntangled : new StatusAffectType('Minotaur Entangled'),
		MissFirstRound : new StatusAffectType('miss first round'),
		NoLoot : new StatusAffectType('No Loot'),
		PCTailTangle : new StatusAffectType('PCTailTangle'),
		PeachLootLoss : new StatusAffectType('Peach Loot Loss'),
		// @aimozg i don't know and do not fucking care if these two should be merged
		PhyllaFight : new StatusAffectType('PhyllaFight'),
		phyllafight : new StatusAffectType('phyllafight'),
		Platoon : new StatusAffectType('platoon'),
		QueenBind : new StatusAffectType('QueenBind'),
		// @aimozg HA HA HA
		Round : new StatusAffectType('Round'),
		round : new StatusAffectType('round'),
		RunDisabled : new StatusAffectType('Run Disabled'),
		Shell : new StatusAffectType('Shell'),
		SirenSong : new StatusAffectType('Siren Song'),
		Spar : new StatusAffectType('spar'),
		Sparring : new StatusAffectType('sparring'),
		spiderfight : new StatusAffectType('spiderfight'),
		StunCooldown : new StatusAffectType('Stun Cooldown'),
		TentacleCoolDown : new StatusAffectType('TentacleCoolDown'),
		Timer : new StatusAffectType('Timer'),
		Uber : new StatusAffectType('Uber'),
		UrtaSecondWinded : new StatusAffectType('Urta Second Winded'),
		UsedTitsmother : new StatusAffectType('UsedTitsmother'),
		Vala : new StatusAffectType('vala'),
		Vapula : new StatusAffectType('Vapula'),
		WhipReady : new StatusAffectType('Whip Ready'),

		// combat
		AcidSlap : new CombatStatusAffect('Acid Slap'),
		AkbalSpeed : new CombatStatusAffect('Akbal Speed'),
		AmilyVenom : new CombatStatusAffect('Amily Venom'),
		AnemoneVenom : new CombatStatusAffect('Anemone Venom'),
		AttackDisabled : new CombatStatusAffect('Attack Disabled'),
		BasiliskCompulsion : new CombatStatusAffect('Basilisk Compulsion'),
		BasiliskSlow : new CombatStatusAffect('BasiliskSlow'),
		Berzerking : new CombatStatusAffect('Berzerking'),
		Blind : new CombatStatusAffect('Blind'),
		Bound : new CombatStatusAffect('Bound'),
		CalledShot : new CombatStatusAffect('Called Shot'),
		ChargeWeapon : new CombatStatusAffect('Charge Weapon'),
		Chokeslam : new CombatStatusAffect('Chokeslam'),
		Confusion : new CombatStatusAffect('Confusion'),
		DemonSeed : new CombatStatusAffect('DemonSeed'),
		Disarmed : new CombatStatusAffect('Disarmed'),
		DriderKiss : new CombatStatusAffect('Drider Kiss'),
		FirstAttack : new CombatStatusAffect('FirstAttack'),
		GnollSpear : new CombatStatusAffect('Gnoll Spear'),
		GooArmorBind : new CombatStatusAffect('GooArmorBind'),
		GooArmorSilence : new CombatStatusAffect('GooArmorSilence'),
		GooBind : new CombatStatusAffect('GooBind'),
		HarpyBind : new CombatStatusAffect('HarpyBind'),
		HolliConstrict : new CombatStatusAffect('Holli Constrict'),
		InfestAttempted : new CombatStatusAffect('infestAttempted'),
		IsabellaStunned : new CombatStatusAffect('Isabella Stunned'),
		IzmaBleed : new CombatStatusAffect('Izma Bleed'),
		KissOfDeath : new CombatStatusAffect('Kiss of Death'),
		LustStones : new CombatStatusAffect('lust stones'),
		lustvenom : new CombatStatusAffect('lust venom'),
		Might : new CombatStatusAffect('Might'),
		NagaBind : new CombatStatusAffect('Naga Bind'),
		NagaVenom : new CombatStatusAffect('Naga Venom'),
		NoFlee : new CombatStatusAffect('NoFlee'),
		ParalyzeVenom : new CombatStatusAffect('paralyze venom'),
		PhysicalDisabled : new CombatStatusAffect('Physical Disabled'),
		Poison : new CombatStatusAffect('Poison'),
		Sandstorm : new CombatStatusAffect('sandstorm'),
		Sealed : new CombatStatusAffect('Sealed'),
		SheilaOil : new CombatStatusAffect('Sheila Oil'),
		Shielding : new CombatStatusAffect('Sheilding'),
		StoneLust : new CombatStatusAffect('Stone Lust'),
		Stunned : new CombatStatusAffect('Stunned'),
		TailWhip : new CombatStatusAffect('Tail Whip'),
		TemporaryHeat : new CombatStatusAffect('Temporary Heat'),
		TentacleBind : new CombatStatusAffect('TentacleBind'),
		ThroatPunch : new CombatStatusAffect('Throat Punch'),
		Titsmother : new CombatStatusAffect('Titsmother'),
		TwuWuv : new CombatStatusAffect('Twu Wuv'),
		UBERWEB : new CombatStatusAffect('UBERWEB'),
		Web : new CombatStatusAffect('Web'),
		WebSilence : new CombatStatusAffect('Web-Silence'),
		Whispered : new CombatStatusAffect('Whispered'),
		
		RemovedArmor : new CombatStatusAffect('Removed Armor'),
		JCLustLevel : new CombatStatusAffect('JC Lust Level'),
		MirroredAttack : new CombatStatusAffect('Mirrored Attack'),
		KnockedBack : new CombatStatusAffect('Knocked Back'),
		Tentagrappled : new CombatStatusAffect('Tentagrappled'),
		TentagrappleCooldown : new CombatStatusAffect('Tentagrapple Cooldown'),
		ShowerDotEffect : new CombatStatusAffect('Shower Dot Effect'),
		GardenerSapSpeed : new CombatStatusAffect('Sap Speed'),
		VineHealUsed : new CombatStatusAffect('Vine Heal Used')
	};
});
