'use strict';

angular.module('cocjs').factory('PerkLib', function (PerkType, ResolutePerk, TacticianPerk, WeaponMasteryPerk, ArchmagePerk, BerzerkerPerk, BrutalBlowsPerk, DoubleAttackPerk, ImmovableObjectPerk, LightningStrikesPerk, LungingAttacksPerk, PiercedCrimstonePerk, SluttySeductionPerk, WizardsEndurancePerk, PentUpPerk, WizardsFocusPerk, SpellcastingAffinityPerk, ElvenBountyPerk, ControlledBreathPerk, CleansingPalmPerk, EnlightenedPerk, PiercedFertitePerk) {
	return {
		// UNSORTED perks TODO these are mostly incorrect perks: tested but never created
		Brawler : new PerkType("Brawler", "Brawler", "Brawling experience allows you to make two unarmed attacks in a turn.", "You choose the 'Brawler' perk, allowing you to make two unarmed attacks in a turn!"),
		Buttslut : new PerkType("Buttslut", "Buttslut", ""),
		Focused : new PerkType("Focused", "Focused", ""),
		// Player creation perks
		Fast : new PerkType("Fast", "Fast", "Gains speed 25% faster."),
		Lusty : new PerkType("Lusty", "Lusty", "Gains lust 25% faster."),
		Sensitive : new PerkType("Sensitive", "Sensitive", "Gains sensitivity 25% faster."),
		Smart : new PerkType("Smart", "Smart", "Gains intelligence 25% faster."),
		Strong : new PerkType("Strong", "Strong", "Gains strength 25% faster."),
		Tough : new PerkType("Tough", "Tough", "Gains toughness 25% faster."),
		// Female creation perks
		BigClit : new PerkType("Big Clit", "Big Clit", "Allows your clit to grow larger more easily and faster."),
		BigTits : new PerkType("Big Tits", "Big Tits", "Makes your tits grow larger more easily."),
		Fertile : new PerkType("Fertile", "Fertile", "Makes you 15% more likely to become pregnant."),
		WetPussy : new PerkType("Wet Pussy", "Wet Pussy", "Keeps your pussy wet and provides a bonus to capacity."),
		// Male creation perks
		BigCock : new PerkType("Big Cock", "Big Cock", "Gains cock size 25% faster and with less limitations."),
		MessyOrgasms : new PerkType("Messy Orgasms", "Messy Orgasms", "Produces 50% more cum volume."),
		// History perks
		HistoryAlchemist : new PerkType("History: Alchemist", "History: Alchemist", "Alchemical experience makes items more reactive to your body."),
		HistoryFighter : new PerkType("History: Fighter", "History: Fighter", "A Past full of conflict increases physical damage dealt by 10%."),
		HistoryHealer : new PerkType("History: Healer", "History: Healer", "Healing experience increases HP gains by 20%."),
		HistoryReligious : new PerkType("History: Religious", "History: Religious", "Replaces masturbate with meditate when corruption less than or equal to 66."),
		HistoryScholar : new PerkType("History: Scholar", "History: Scholar", "Time spent focusing your mind makes spellcasting 20% less fatiguing."),
		HistorySlacker : new PerkType("History: Slacker", "History: Slacker", "Regenerate fatigue 20% faster."),
		HistorySlut : new PerkType("History: Slut", "History: Slut", "Sexual experience has made you more able to handle large insertions and more resistant to stretching."),
		HistorySmith : new PerkType("History: Smith", "History: Smith", "Knowledge of armor and fitting increases armor effectiveness by roughly 10%."),
		HistoryWhore : new PerkType("History: Whore", "History: Whore", "Seductive experience causes your tease attacks to be 15% more effective."),
		// Ordinary (levelup) perks
		Acclimation : new PerkType("Acclimation", "Acclimation", "Reduces lust gain by 15%.", "You choose the 'Acclimation' perk, making your body 15% more resistant to lust, up to a maximum of 75%."),
		Agility : new PerkType("Agility", "Agility", "Boosts armor points by a portion of your speed on light/medium armors.", "You choose the 'Agility' perk, increasing the effectiveness of Light/Medium armors by a portion of your speed."),
		Archmage : new ArchmagePerk(),
		ArousingAura : new PerkType("Arousing Aura", "Arousing Aura", "Exude a lust-inducing aura (Req's corruption of 70 or more)", "You choose the 'Arousing Aura' perk, causing you to radiate an aura of lust when your corruption is over 70."),
		Berzerker : new BerzerkerPerk(),
		BrutalBlows : new BrutalBlowsPerk(),
		Channeling : new PerkType("Channeling", "Channeling", "Increases base spell strength by 50%.", "You choose the 'Channeling' perk, boosting the strength of your spellcasting!"),
		CorruptedLibido : new PerkType("Corrupted Libido", "Corrupted Libido", "Reduces lust gain by 10%.", "You choose the 'Corrupted Libido' perk.  As a result of your body's corruption, you've become a bit harder to turn on. (Lust gain reduced by 10%!)"),
		DoubleAttack : new DoubleAttackPerk(),
		Evade : new PerkType("Evade", "Evade", "Increases chances of evading enemy attacks.", "You choose the 'Evade' perk, allowing you to avoid enemy attacks more often!"),
		FertilityPlus : new PerkType("Fertility+", "Fertility+", "Increases fertility rating by 15 and cum volume by up to 50%.", "You choose the 'Fertility+' perk, making it easier to get pregnant.  It also increases your cum volume by up to 50% (if appropriate)!"),
		HotBlooded : new PerkType("Hot Blooded", "Hot Blooded", "Raises minimum lust by up to 20.", "You choose the 'Hot Blooded' perk.  As a result of your enhanced libido, your lust no longer drops below 20! (If you already have some minimum lust, it will be increased by 10)"),
		ImmovableObject : new ImmovableObjectPerk(),
		IronMan : new PerkType("Iron Man", "Iron Man", "Reduces the fatigue cost of physical specials by 50%.", "You choose the 'Iron Man' perk, reducing the fatigue cost of physical special attacks by 50%"),
		LightningStrikes : new LightningStrikesPerk(),
		LungingAttacks : new LungingAttacksPerk(),
		Mage : new PerkType("Mage", "Mage", "Increases base spell strength by 50%.", "You choose the 'Mage' perk.  You are able to focus your magical abilities even more keenly, boosting your base spell effects by 50%."),
		Masochist : new PerkType("Masochist", "Masochist", "Take 30% less physical damage but gain lust when damage.", "You choose the 'Masochist' perk, reducing the damage you take but raising your lust each time!  This perk only functions while your libido is at or above 60!"),
		Medicine : new PerkType("Medicine", "Medicine", "Grants 15% chance per round of cleansing poisons/drugs from your body.", "You choose the 'Medicine' perk, giving you a chance to remove debilitating poisons automatically!"),
		Nymphomania : new PerkType("Nymphomania", "Nymphomania", "Raises minimum lust by up to 30.", "You've chosen the 'Nymphomania' perk.  Due to the incredible amount of corruption you've been exposed to, you've begun to live in a state of minor constant arousal.  Your minimum lust will be increased by as much as 30 (If you already have minimum lust, the increase is 10-15)."),
		Precision : new PerkType("Precision", "Precision", "Reduces enemy armor by 10. (Req's 25+ Intelligence)", "You've chosen the 'Precision' perk.  Thanks to your intelligence, you're now more adept at finding and striking an enemy's weak points, reducing their damage resistance from armor by 10.  If your intelligence ever drops below 25 you'll no longer be smart enough to benefit from this perk."),
		Regeneration : new PerkType("Regeneration", "Regeneration", "Regenerates 2% of max HP/hour and 1% of max HP/round.", "You choose the 'Regeneration' perk, allowing you to heal 2% of max HP every hour and 1% of max HP every round of combat!"),
		Regeneration2 : new PerkType("Regeneration 2", "Regeneration 2", "Gain 2% of max HP per round of combat and 4% of max HP per hour out of combat.", "You choose the 'Regeneration 2' perk, giving you an additional 2% of max HP per turn in combat and 4% of max HP per hour."),
		Resistance : new PerkType("Resistance", "Resistance", "Reduces lust gain by 10%.", "You choose the 'Resistance' perk, reducing the rate at which your lust increases by 10%."),
		Resolute : new ResolutePerk(),
		Runner : new PerkType("Runner", "Runner", "Increases chances of escaping combat.", "You choose the 'Runner' perk, increasing your chances to escape from your foes when fleeing!"),
		Sadist : new PerkType("Sadist", "Sadist", "Deal 20% more damage, but gain lust at the same time.", "You choose the 'Sadist' perk, increasing damage by 20 percent but causing you to gain lust from dealing damage."),
		Seduction : new PerkType("Seduction", "Seduction", "Upgrades your tease attack, making it more effective.", "You choose the 'Seduction' perk, upgrading the 'tease' attack with a more powerful damage and a higher chance of success."),
		SpeedyRecovery : new PerkType("Speedy Recovery", "Speedy Recovery", "Regain fatigue 50% faster.", "You choose the 'Speedy Recovery' perk, boosting your fatigue recovery rate!"),
		Spellpower : new PerkType("Spellpower", "Spellpower", "Increases base spell strength by 50%.", "You choose the 'Spellpower' perk.  Thanks to your sizeable intellect and willpower, you are able to more effectively use magic, boosting base spell effects by 50%."),
		StrongBack : new PerkType("Strong Back", "Strong Back", "Enables fourth item slot.", "You choose the 'Strong Back' perk, enabling a fourth item slot."),
		StrongBack2 : new PerkType("Strong Back 2: Strong Harder", "Strong Back 2: Strong Harder", "Enables fifth item slot.", "You choose the 'Strong Back 2: Strong Harder' perk, enabling a fifth item slot."),
		Tactician : new TacticianPerk(),
		Tank : new PerkType("Tank", "Tank", "Raises max HP by 50.", "You choose the 'Tank' perk, giving you an additional 50 hp!"),
		Tank2 : new PerkType("Tank 2", "Tank 2", "+1 extra HP per point of toughness.", "You choose the 'Tank 2' perk, granting an extra maximum HP for each point of toughness."),
		ThunderousStrikes : new PerkType("Thunderous Strikes", "Thunderous Strikes", "+20% 'Attack' damage while strength is at or above 80.", "You choose the 'Thunderous Strikes' perk, increasing normal damage by 20% while your strength is over 80."),
		WeaponMastery : new WeaponMasteryPerk(),
		WellAdjusted : new PerkType("Well Adjusted", "Well Adjusted", "You gain half as much lust as time passes in Mareth.", "You choose the 'Well Adjusted' perk, reducing the amount of lust you naturally gain over time while in this strange land!"),
		// Needlework perks
		ChiReflowAttack : new PerkType("Chi Reflow - Attack", "Chi Reflow - Attack", "Regular attacks boosted, but damage resistance decreased."),
		ChiReflowDefense : new PerkType("Chi Reflow - Defense", "Chi Reflow - Defense", "Passive damage resistance, but caps speed"),
		ChiReflowLust : new PerkType("Chi Reflow - Lust", "Chi Reflow - Lust", "Lust resistance and Tease are enhanced, but Libido and Sensitivity gains increased."),
		ChiReflowMagic : new PerkType("Chi Reflow - Magic", "Chi Reflow - Magic", "Magic attacks boosted, but regular attacks are weaker."),
		ChiReflowSpeed : new PerkType("Chi Reflow - Speed", "Chi Reflow - Speed", "Speed reductions are halved but caps strength"),
		// Piercing perks
		PiercedCrimstone : new PiercedCrimstonePerk(),
		PiercedFertite : new PiercedFertitePerk(),
		PiercedFurrite : new PerkType("Pierced: Furrite", "Pierced: Furrite", "Increases chances of encountering 'furry' foes."),
		PiercedLethite : new PerkType("Pierced: Lethite", "Pierced: Lethite", "Increases chances of encountering demonic foes."),
		// Cock sock perks
		LustyRegeneration : new PerkType("Lusty Regeneration", "Lusty Regeneration", "Regenerates 1% of HP per round in combat and 2% of HP per hour."),
		MidasCock : new PerkType("Midas Cock", "Midas Cock", "Increases the gems awarded from victory in battle."),
		PentUp : new PentUpPerk(),
		PhallicPotential : new PerkType("Phallic Potential", "Phallic Potential", "Increases the effects of penis-enlarging transformations."),
		PhallicRestraint : new PerkType("Phallic Restraint", "Phallic Restraint", "Reduces the effects of penis-enlarging transformations."),
		// Armor perks
		BloodMage : new PerkType("Blood Mage", "Blood Mage", "Spellcasting now consumes health instead of fatigue!"),
		SluttySeduction : new SluttySeductionPerk(),
		WizardsEndurance : new WizardsEndurancePerk(),
		// Weapon perks
		WizardsFocus : new WizardsFocusPerk(),
		// Achievement perks
		BroodMother : new PerkType("Brood Mother", "Brood Mother", "Pregnancy moves twice as fast as a normal woman's."),
		SpellcastingAffinity : new SpellcastingAffinityPerk(),
		// Mutation perks
		Androgyny : new PerkType("Androgyny", "Androgyny", "No gender limits on facial masculinity or femininity."),
		BasiliskWomb : new PerkType("Basilisk Womb", "Basilisk Womb", "Enables your eggs to be properly fertilized into basilisks of both genders!"),
		BeeOvipositor : new PerkType("Bee Ovipositor", "Bee Ovipositor", "Allows you to lay eggs through a special organ on your insect abdomen, though you need at least 10 eggs to lay."),
		BimboBody : new PerkType("Bimbo Body", "Bimbo Body", "Gives the body of a bimbo.  Tits will never stay below a 'DD' cup, libido is raised, lust resistance is raised, and upgrades tease."),
		BimboBrains : new PerkType("Bimbo Brains", "Bimbo Brains", "Now that you've drank bimbo liquer, you'll never, like, have the attention span and intelligence you once did!  But it's okay, 'cause you get to be so horny an' stuff!"),
		BroBody : new PerkType("Bro Body", "Bro Body", "Grants an ubermasculine body that's sure to impress."),
		BroBrains : new PerkType("Bro Brains", "Bro Brains", "Makes thou... thin... fuck, that shit's for nerds."),
		BunnyEggs : new PerkType("Bunny Eggs", "Bunny Eggs", "Laying eggs has become a normal part of your bunny-body's routine."),
		CorruptedNinetails : new PerkType("Corrupted Nine-tails", "Corrupted Nine-tails", "The mystical energy of the nine-tails surges through you, filling you with phenomenal cosmic power!  Your boundless magic allows you to recover quickly after casting spells, but your method of attaining it has corrupted the transformation, preventing you from achieving true enlightenment."),
		Diapause : new PerkType("Diapause", "Diapause", "Pregnancy does not advance normally, but develops quickly after taking in fluids."),
		Dragonfire : new PerkType("Dragonfire", "Dragonfire", "Allows access to a dragon breath attack."),
		EnlightenedNinetails : new PerkType("Enlightened Nine-tails", "Enlightened Nine-tails", "The mystical energy of the nine-tails surges through you, filling you with phenomenal cosmic power!  Your boundless magic allows you to recover quickly after casting spells."),
		Feeder : new PerkType("Feeder", "Feeder", "Lactation does not decrease and gives a compulsion to breastfeed others."),
		Flexibility : new PerkType("Flexibility", "Flexibility", "Grants cat-like flexibility.  Useful for dodging and 'fun'."),
		FutaFaculties : new PerkType("Futa Faculties", "Futa Faculties", "It's super hard to think about stuff that like, isn't working out or fucking!"),
		FutaForm : new PerkType("Futa Form", "Futa Form", "Ensures that your body fits the Futa look (Tits DD+, Dick 8\"+, & Pussy).  Also keeps your lusts burning bright and improves the tease skill."),
		HarpyWomb : new PerkType("Harpy Womb", "Harpy Womb", "Increases all laid eggs to large size so long as you have harpy legs and a harpy tail."),
		Incorporeality : new PerkType("Incorporeality", "Incorporeality", "Allows you to fade into a ghost-like state and temporarily possess others."),
		MinotaurCumAddict : new PerkType("Minotaur Cum Addict", "Minotaur Cum Addict", "Causes you to crave minotaur cum frequently.  You cannot shake this addiction."),
		Oviposition : new PerkType("Oviposition", "Oviposition", "Causes you to regularly lay eggs when not otherwise pregnant."),
		PurityBlessing : new PerkType("Purity Blessing", "Purity Blessing", "Reduces the rate at which your corruption, libido, and lust increase."),
		SlimeCore : new PerkType("Slime Core", "Slime Core", "Grants more control over your slimy body, allowing you to go twice as long without fluids."),
		SpiderOvipositor : new PerkType("Spider Ovipositor", "Spider Ovipositor", "Allows you to lay eggs through a special organ on your arachnid abdomen, though you need at least 10 eggs to lay."),
		ThickSkin : new PerkType("Thick Skin", "Thick Skin", "Toughens your dermis to provide 2 points of armor."),
		// Quest, Event & NPC perks
		BulgeArmor : new PerkType("Bulge Armor", "Bulge Armor", "Grants a 5 point damage bonus to dick-based tease attacks."),
		Cornucopia : new PerkType("Cornucopia", "Cornucopia", "Vaginal and Anal capacities increased by 30."),
		ElvenBounty : new ElvenBountyPerk(),
		FerasBoonAlpha : new PerkType("Fera's Boon - Alpha", "Fera's Boon - Alpha", "Increases the rate your cum builds up and cum production in general."),
		FerasBoonBreedingBitch : new PerkType("Fera's Boon - Breeding Bitch", "Fera's Boon - Breeding Bitch", "Increases fertility and reduces the time it takes to birth young."),
		FerasBoonMilkingTwat : new PerkType("Fera's Boon - Milking Twat", "Fera's Boon - Milking Twat", "Keeps your pussy from ever getting too loose and increases pregnancy speed.", "Keeps your pussy from ever getting too loose and increases pregnancy speed."),
		FerasBoonSeeder : new PerkType("Fera's Boon - Seeder", "Fera's Boon - Seeder", "Increases cum output by 1,000 mLs.", "Increases cum output by 1,000 mLs."),
		FerasBoonWideOpen : new PerkType("Fera's Boon - Wide Open", "Fera's Boon - Wide Open", "Keeps your pussy permanently gaped and increases pregnancy speed.", "Keeps your pussy permanently gaped and increases pregnancy speed."),
		FireLord : new PerkType("Fire Lord", "Fire Lord", "Akbal's blessings grant the ability to breathe burning green flames."),
		Hellfire : new PerkType("Hellfire", "Hellfire", "Grants a corrupted fire breath attack, like the hellhounds in the mountains."),
		LuststickAdapted : new PerkType("Luststick Adapted", "Luststick Adapted", "Grants immunity to the lust-increasing effects of lust-stick and allows its use."),
		MagicalFertility : new PerkType("Magical Fertility", "Magical Fertility", "10% higher chance of pregnancy and increased pregnancy speed.", "10% higher chance of pregnancy and increased pregnancy speed."),
		MagicalVirility : new PerkType("Magical Virility", "Magical Virility", "200 mLs more cum per orgasm and enhanced virility.", "200 mLs more cum per orgasm and enhanced virility."),
		MaraesGiftButtslut : new PerkType("Marae's Gift - Buttslut", "Marae's Gift - Buttslut", "Makes your anus provide lubrication when aroused."),
		MaraesGiftFertility : new PerkType("Marae's Gift - Fertility", "Marae's Gift - Fertility", "Greatly increases fertility and halves base pregnancy speed."),
		MaraesGiftProfractory : new PerkType("Marae's Gift - Profractory", "Marae's Gift - Profractory", "Causes your cum to build up at 3x the normal rate."),
		MaraesGiftStud : new PerkType("Marae's Gift - Stud", "Marae's Gift - Stud", "Increases your cum production and potency greatly."),
		MarbleResistant : new PerkType("Marble Resistant", "Marble Resistant", "Provides resistance to the addictive effects of bottled LaBova milk."),
		MarblesMilk : new PerkType("Marble's Milk", "Marble's Milk", "Requires you to drink LaBova milk frequently or eventually die.  You cannot shake this addiction."),
		Misdirection : new PerkType("Misdirection", "Misdirection", "Grants additional evasion chances while wearing Raphael's red bodysuit."),
		OmnibusGift : new PerkType("Omnibus' Gift", "Omnibus' Gift", "Increases minimum lust but provides some lust resistance."),
		OneTrackMind : new PerkType("One Track Mind", "One Track Mind", "Your constant desire for sex causes your sexual organs to be able to take larger insertions and disgorge greater amounts of fluid."),
		PilgrimsBounty : new PerkType("Pilgrim's Bounty", "Pilgrim's Bounty", "Causes you to always cum as hard as if you had max lust."),
		PureAndLoving : new PerkType("Pure and Loving", "Pure and Loving", "Your caring attitude towards love and romance makes you slightly more resistant to lust and corruption."),
		SensualLover : new PerkType("Sensual Lover", "Sensual Lover", "Your sensual attitude towards love and romance makes your tease ability slightly more effective."),
		Whispered : new PerkType("Whispered", "Whispered", "Akbal's blessings grant limited telepathy that can induce fear."),
		ControlledBreath : new ControlledBreathPerk(),
		CleansingPalm : new CleansingPalmPerk(),
		Enlightened : new EnlightenedPerk(),
		// Monster perks
		Acid : new PerkType("Acid", "Acid", "")
	};
});
